#!/bin/bash

random_number() {
MATRIX="0123456789abcdefghijklmnopqrstuvwxyz" 
LENGTH="10"
while [ "${n:=1}" -le "$LENGTH" ]
do
        PASS="$PASS${MATRIX:$(($RANDOM%${#MATRIX})):1}"
        let n+=1
done
        echo "$PASS"
exit 0
}

mkdir -p ROM

if [ "$3" = "" ]
then
echo you must input device name and build number
elif [ -e "$3" -a "$1" = "c" ]
then
cp ./out/fullota.zip ./ROM/miui_"$2"_"$3"_"$OTA"_4.0.zip
else
if [ ! -e ./ROM/target_files_"$3".zip ]
then
echo -e "\E[32m last target_files_"$3".zip don't exists \E[0m"
exit 0
fi
if [ ! -e ./ROM/target_files_"$2".zip ]
then
cp ./out/target_files.zip ./ROM/target_files_"$2".zip
echo copy target_files.zip from out_dir
else
echo target_files.zip already exists
fi
../../tools/releasetools/ota_from_target_files -k ../../build/security/testkey -i ./ROM/target_files_"$3".zip ./ROM/target_files_"$2".zip ./ROM/ota_upate.zip
OTA=`random_number`
ZIP=`random_number`
mv ./ROM/ota_upate.zip ./ROM/miui-ota-"$1"-"$3"-"$2"-"$ZIP"-4.0.zip
if [ "$1" = "c8812" -o "$1" = "u8818" ]
then
echo -e "\E[32m use custom key \E[0m"
sign -g ./ROM/miui_"$1"_"$2"_"$OTA"_4.0.zip
sign -g ./ROM/miui-ota-"$1"-"$3"-"$2"-"$ZIP"-4.0.zip
fi
fi
